# Generated by Django 5.1.5 on 2025-02-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_sysuser_user_ptr_remove_usage_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='buying_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
