# Generated by Django 5.1.5 on 2025-02-19 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_material_buying_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkOrder',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='Sales',
            new_name='Sale',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_type',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='photo',
        ),
    ]
