# Generated by Django 5.1.5 on 2025-02-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_workorder_order_rename_sales_sale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sales_date',
            field=models.DateField(),
        ),
    ]
