# Generated by Django 5.1.5 on 2025-03-13 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_order_order_date_alter_sale_sales_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='unit_price',
            new_name='selling_price',
        ),
    ]
