# Generated by Django 5.1.5 on 2025-03-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_order_price_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.PositiveIntegerField(),
        ),
    ]
