# Generated by Django 5.1.5 on 2025-03-28 13:26

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_employee_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='purchase_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 28, 13, 25, 21, 361498)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='purchase_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(default='0932177191', max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\d{9,15}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_code',
            field=models.CharField(max_length=50),
        ),
    ]
