# Generated by Django 5.1.5 on 2025-03-29 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='expected_sale',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
